import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Portfolio Reytama",
  description: "Blog portfolio generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="transition-colors duration-300">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
