import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Portfolio Reytama",
  description: "Blog portofolio Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white text-black dark:bg-[#1a1c23] dark:text-white transition-colors duration-300">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
